name: test! Scheduled 

on:
  schedule:
    # GitHub uses UTC. (+8 hours for Malaysia)
    - cron: '0 20 * * *'  # 5:00 AM MYT (Poster A)
    - cron: '0 4 * * *'   # 12:00 PM MYT (Poster A)
    - cron: '0 13 * * *'  # 9:00 PM MYT (Poster B)
  workflow_dispatch:      # Allows you to run it manually for testing

jobs:
  post-video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyTelegramBotAPI

      - name: Run Poster A (5am & 12pm)
        if: github.event.schedule == '0 21 * * *' || github.event.schedule == '0 4 * * *' || github.event_name == 'workflow_dispatch'
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot2.py POSTER_A

      - name: Run Poster B (9pm)
        if: github.event.schedule == '0 13 * * *'
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot2.py POSTER_B
