name: Telegram Daily Scheduler

on:
  schedule:
    # 21:00 UTC (5am MYT), 01:00 UTC (9am MYT), 04:00 UTC (12pm MYT)
    - cron: '0 21,1,4 * * *'
  workflow_dispatch: # This allows you to click the button to test manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Libraries
        run: pip install pyTelegramBotAPI pytz

      - name: Execute Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py
