import os
import telebot

# Get credentials from GitHub Secrets
TOKEN = os.getenv('TELEGRAM_TOKEN')
CHAT_ID = os.getenv('CHAT_ID')
bot = telebot.TeleBot(TOKEN)

# Path to your video
VIDEO_PATH = "posters/poster_a.MP4"

def main():
    print("Attempting to send video...")
    try:
        with open(VIDEO_PATH, 'rb') as video:
            bot.send_video(CHAT_ID, video)
        print("Success! Video sent to Telegram.")
    except Exception as e:
        print(f"Error occurred: {e}")

if __name__ == "__main__":
    main()
